### ISSUE TITLE
SHA256 for LSH instead of np.packbits

### ISSUE THREAD

**Issue by roman-bushuiev** [pluskal-lab/DreaMS#2]
Hi @tornikeo! I did some work related to your pull request (https://github.com/pluskal-lab/DreaMS/pull/1) and just want to let you know that I’ve updated the method for handling LSH binary arrays (1fdffa2361c32f6536a2a9064f2e7719f77482c3 and 9e346ce0ac2c99e6ec2a4f0b57a32dda77b145d5). Instead of converting the arrays to integers using `np.packbits`, they are now converted to strings and hashed with SHA256. This allows for using an arbitrary number of hyperplanes (not necessarily divisible by 64) and should result in fewer collisions without affecting computation time.

**Comment by tornikeo** [comment]
@roman-bushuiev Hey. That's neat. I tried something similar in my own project:

```py
@lru_cache
def _random_kernel(n_elem, n_planes):
    random_state = np.random.RandomState(42)
    # Generate the random normal matrix
    random_matrix = random_state.normal(size=(n_elem, n_planes))
    return random_matrix

def hash_spectrum(
    peaks_mz,
    peak_intensities,
    num_planes=512,
    min_mz=1e-4,
    max_mz=1e3,
    num_bins=2048,
):
    kernel = _random_kernel(
        num_bins,
        num_planes,
    )
    b_peaks = bin_spectrum(
        peaks_mz, peak_intensities, min_mz, max_mz, num_bins
    ).reshape(1, -1)
    proj = b_peaks @ kernel >= 0
    proj_signs_u64 = np.packbits(proj, axis=1).view(np.uint64) # N, (n_hyp//8)
    buffer = proj_signs_u64[0].data.tobytes()
    hash_ = np.int64(int(hashlib.md5(buffer).hexdigest(), 16) % (2**62))
    return hash_
```

It's basically a `functional`-style hashing for spectrum.  I have yet to test it out "in the wild" though. Also the last bit `% (2**62))` is a bit questionable, but I don't want any overflows in `np.int64` :sweat_smile:
